version: '3.9'

services:
  web_prod:
    image: ghcr.io/deimos715/yuor_repository:latest # репозиторий
    container_name: django_prod_apps # изменить для другого проекта
    environment: 
      DJANGO_ENV: prod # настройки для prod
    env_file:
      - core/settings/.env.prod # рекомендуется указывать .env.prod
    command: >
      sh -c "python manage.py migrate && python manage.py collectstatic --noinput &&
            gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 60"

    volumes:
      - /var/www/userlab/data/webdevlabs/staticfiles:/app/staticfiles
      - /var/www/userlab/data/webdevlabs/media:/app/media
    expose:
      - '8000'
    ports:
      - '127.0.0.1:8001:8000'   # внешний Nginx (FastPanel) проксирует на этот порт (если два сайта и более, указываем порт по порядку 8002,...)
    depends_on:
      - db_prod
    networks:
      - prod_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://127.0.0.1:8000/health || exit 1']
      interval: 30s
      timeout: 5s
      retries: 5

  db_prod:
    image: postgres:17
    container_name: postgres_prod # изменить postgres_dev для другого проекта
    env_file:
      - core/settings/.env.prod # рекомендуется указывать .env.prod
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data # изменить postgres_prod для другого проекта
    networks:
      - prod_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB" -h 127.0.0.1']
      interval: 10s
      timeout: 5s
      retries: 10

  # redis_prod:
  #   image: redis:7-alpine
  #   container_name: redis_prod
  #   networks:
  #     - prod_network
  #   restart: unless-stopped

volumes:
  postgres_prod_data: # изменить postgres_prod для другого проекта

networks:
  prod_network:
    driver: bridge
